# Generated by Django 5.0.6 on 2024-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_kra_document_user_passport_photo_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="blog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="blogs/videos/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
